#-------------------------------
# General Site Settings
title: Thi Huỳnh
logo: logo.png # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Thi Huỳnh
  image: 01.jpg
  say-hello: Hello, I’m <strong>Thi Huỳnh</strong>
  bio: Designs, talks, and writes about <strong>website</strong>, <strong>privacy</strong>, and dev. I share website design tutorials, free resources and inspiration. Loves <a href="#">soccer</a> & camping...


#-------------------------------
# Contact links
facebook: https://facebook.com/huynhtanthi # Add your Facebook handle
youtube: https://www.youtube.com/@thihuynh82
twitter: https://twitter.com/huynhtanthi # Add your Twitter handle
linkedin: https://www.linkedin.com/in/thiit/ # Add your Linkedin handle
instagram: https://www.instagram.com/thihuynh1217 # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: Mr. Thi # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: thihuynh1217 # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
